---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart flaskapp
  ansible.builtin.service:
    name: flaskapp
    state: restarted
  become: true